End implementation of VPN commands

diff --git a/dom0/risk b/dom0/risk
--- a/dom0/risk
+++ b/dom0/risk
@@ -1755,6 +1755,79 @@ function _catch ()
     fi
 }
 
+#assertRunning [vm] [start]
+#Assert that the given VM is running. Will unpause paused VMs and may start shut down VMs.
+#[vm]: VM for which to make sure it's running.
+#[start]: If it's not running and not paused, start it (default: 0/true). If set to 1, this function will return a non-zero exit code.
+#returns: A non-zero exit code, if it's not running and/or we failed to start the VM.
+function assertRunning {
+    local vm="$1"
+    local start="${2:-0}"
+
+    #make sure the VM is unpaused
+    if qvm-check --paused "$vm" &> /dev/null ; then
+        qvm-unpause "$vm" &> /dev/null || return 1
+    else
+        if [ $start -eq 0 ] ; then
+            qvm-start --skip-if-running "$vm" &> /dev/null || return 1
+        else
+            #we don't attempt to start
+            return 2
+        fi
+    fi
+
+    return 0
+}
+
+# start_vm [vm 1] ... [vm n]
+#Start the given VMs without executing any command.
+function start_vm {
+    local ret=0
+
+    local vm=
+    declare -A pids=() #VM --> pid
+    for vm in "$@" ; do
+        [[ "$vm" == "dom0" ]] && continue
+        _verbose "Starting: $vm"
+        assertRunning "$vm" &
+        pids["$vm"]=$!
+    done
+
+    local failed=""
+    local ret=
+    for vm in "${!pids[@]}" ; do
+        wait "${pids["$vm"]}"
+        ret=$?
+        [ $ret -ne 0 ] && failed="$failed"$'\n'"$vm ($ret)"
+    done
+
+    [ -z "$failed" ] || _verbose "Starting the following VMs failed: $failed"
+
+    #set exit code
+    [ -z "$failed" ]
+}
+
+# shutdown_vm [vm 1] ... [vm n]
+#Shut the given VMs down.
+function shutdown_vm {
+    local ret=0
+
+    if [ $# -gt 0 ] ; then
+        #make sure the VMs are unpaused
+        #cf. https://github.com/QubesOS/qubes-issues/issues/5967
+        local vm=
+        for vm in "$@" ; do
+            qvm-unpause "$vm" &> /dev/null
+        done
+
+        _verbose "Shutting down: $*"
+        qvm-shutdown --wait "$@"
+        ret=$?
+    fi
+
+    return $ret
+}
+
 # src/lib/tor_gateway.sh
 
 # Creates a new TOR Whonix gateway AppVM.
@@ -1893,7 +1966,7 @@ validate_not_empty() {
 # src/lib/validations/validate_vm.sh
 
 # does the vm exist?
-validate_vm_exits () {
+validate_vm_exists () {
     vm=""
     for item in $(qvm-ls | grep -v dom0 | awk '{print $1}' | grep "${1}")
     do
@@ -2558,7 +2631,7 @@ risk_vpn_setup_command() {
       # If we are asked to choose an existing configuration in the VM
       _qvrun "$name" /usr/local/bin/setup_VPN
 
-  elif [[ -n "${config_vm}" ]]; then
+  elif [[ -n "${args[--config-in]}" ]]; then
       # Or if we are asked to browse one or more configuration files in another VM.
       import_vpn_configs "$name" "$config_vm" "$client_conf_path"
   fi
@@ -2568,20 +2641,26 @@ risk_vpn_setup_command() {
 # :command.function
 risk_vpn_start_command() {
   # src/vpn_start_command.sh
-  echo "# this file is located in 'src/vpn_start_command.sh'"
-  echo "# code for 'risk vpn start' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+
+  local name="${args[vm]}"
+
+  _message "Starting gateway $name in the background"
+  start_vm "$name"
+  _catch "Failed to start $name"
+  _message "Started VM $name"
 
 }
 
 # :command.function
 risk_vpn_stop_command() {
   # src/vpn_stop_command.sh
-  echo "# this file is located in 'src/vpn_stop_command.sh'"
-  echo "# code for 'risk vpn stop' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+
+  local name="${args[vm]}"
+
+  _message "Shutting down gateway $name"
+  shutdown_vm "$name"
+  _catch "Failed to shutdown $name"
+  _message "Shut down $name"
 
 }
 
@@ -2628,10 +2707,40 @@ risk_vpn_disable_command() {
 # :command.function
 risk_vpn_delete_command() {
   # src/vpn_delete_command.sh
-  echo "# this file is located in 'src/vpn_delete_command.sh'"
-  echo "# code for 'risk vpn delete' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+
+  _set_identity
+
+  local name found proxies
+
+  name="${args[vm]}"
+
+  # Check that the selected VM is indeed one of the identity
+  # proxy VMs, so that we don't accidentally delete another one.
+  proxies=($(_identity_proxies))
+  for proxy in "${proxies[@]}" ; do
+      if [[ $proxy == "$name" ]]; then
+          found=true
+      fi
+  done
+
+  if [[ ! $found ]]; then
+      _message "VM $name is not listed as a VPN gateway. Aborting."
+      exit 1
+  fi
+
+  _message "Deleting gateway VM $name"
+
+  # Delete without asking to confirm
+  echo "y" | _run qvm-remove "$name"
+  _catch "Failed to delete (fully or partially) VM $name"
+
+  # Remove from VMs marked autostart
+  sed -i /"$name"/d "${IDENTITY_DIR}/autostart_vms"
+  # And remove from proxy VMs
+
+  sed -i /"$name"/d "${IDENTITY_DIR}/proxy_vms"
+
+  _message "Deleted $name"
 
 }
 
@@ -4078,6 +4187,11 @@ risk_vpn_setup_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
@@ -4135,6 +4249,11 @@ risk_vpn_start_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
@@ -4192,6 +4311,11 @@ risk_vpn_stop_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
@@ -4249,6 +4373,11 @@ risk_vpn_enable_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
@@ -4306,6 +4435,11 @@ risk_vpn_disable_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
@@ -4363,6 +4497,11 @@ risk_vpn_delete_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[vm]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_vm_exists "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "VM" "$(validate_vm_exists "$1")"
+          exit 1
+        fi
 
         args[vm]=$1
         shift
